language: ruby
rvm:
  - 2.1.0
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - psql -c 'create database recbucks;' -U postgres
  - bundle exec rake db:create
  - bundle exec rake db:migrate 
