development:
  adapter: postgresql
  database: db/development
  host: localhost
  pool: 5
  timeout: 5000
  username: recbucks
  password: scio123

test: &test
  adapter: postgresql
  database: db/test
  host: localhost
  pool: 5
  timeout: 5000
  username: recbucks
  password: scio123

production:
  adapter: postgresql
  database: db/production
  host: localhost
  pool: 5
  timeout: 5000
  username: recbucks
  password: scio123

cucumber:
  <<: *test
